#ifndef ASSEMBLER_CONSTANTS_H
#define ASSEMBLER_CONSTANTS_H

#define MAX_LINE_LENGTH 81
#define MAX_FILE_NAME_LENGTH 50
#define OFF 0
#define ON 1
#define ERROR_CODE -1
#define NO_ERROR_CODE 0
#define MAX_LABEL_LENGTH 31

#endif
